# Secrets in Kubernetes store sensitive configuration data.
# They are useful for:
# - Storing credentials (usernames, passwords, tokens)
# - Storing TLS certificates and keys
# - Storing any sensitive configuration
#
# This secret:
# - Stores a sample secrets.html file (for demonstration only)
# - Shows how to encode content in base64
# - Demonstrates secret mounting in pods
#
# Key components:
# - data: Contains base64-encoded sensitive data
# - metadata.name: Used to reference this secret
# - The content is mounted as a file in the Nginx container
#
# Note: In a real environment, never store sensitive content in YAML files.
# Use a secrets management solution like HashiCorp Vault or cloud provider secrets.

apiVersion: v1
kind: Secret
metadata:
  name: nginx-secrets
  namespace: nginx-demo
type: Opaque
data:
  # This is a base64 encoded string of the secrets.html content
  secrets.html: PCFET0NUWVBFIGh0bWw+PGh0bWw+PGhlYWQ+PHRpdGxlPlNlY3JldCBQYWdlPC90aXRsZT48c3R5bGU+Ym9keXtmb250LWZhbWlseTpBcmlhbCxzYW5zLXNlcmlmO21hcmdpbjowO3BhZGRpbmc6MjBweDtiYWNrZ3JvdW5kOiNmMGYwZjB9aDF7Y29sb3I6IzMzM31we2NvbG9yOiM2NjZ9PC9zdHlsZT48L2hlYWQ+PGJvZHk+PGgxPlNlY3JldCBDb250ZW50PC9oMT48cD5UaGlzIGlzIGEgZGVtb25zdHJhdGlvbiBvZiBob3cgdG8gc2VydmUgc2Vuc2l0aXZlIGNvbnRlbnQgdXNpbmcgS3ViZXJuZXRlcyBTZWNyZXRzLjwvcD48cD5JbiBhIHJlYWwgZW52aXJvbm1lbnQsIHNlY3JldHMgYXJlIHR5cGljYWxseSB1c2VkIHRvIHNldCBlbnZpcm9ubWVudCB2YXJpYWJsZXMgb3Igb3RoZXIgc2Vuc2l0aXZlIGluZm9ybWF0aW9uPC9wPjwvYm9keT48L2h0bWw+